#!/bin/sh
#
# Startup application
#

case "$1" in
 start)
        echo "Starting application..."
        /usr/local/app/startup.sh
        ;;
  stop)
        ;;
  restart|reload)
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
